query {
  currentUser {
    addresses {
      nodes {
        address1
        address2
        alternativePhone
        city
        company
        country {
          isoName
          iso
          iso3
          name
          numcode
          statesRequired
          createdAt
          updatedAt
        }
        createdAt
        firstname
        lastname
        id

        phone
        state {
          name
          abbr
          createdAt
          updatedAt
        }
        stateName
        updatedAt
        zipcode
      }
    }
    billAddress {
      address1
      address2
      alternativePhone
      city
      company
      country {
        isoName
        iso
        iso3
        name
        numcode
        statesRequired
        createdAt
        updatedAt
      }
      createdAt
      firstname
      lastname
      id

      phone
      state {
        name
        abbr
        createdAt
        updatedAt
      }
      stateName
      updatedAt
      zipcode
    }
    createdAt
    currentLoginAt
    defaultAddress {
      address1
      address2
      alternativePhone
      city
      company
      country {
        isoName
        iso
        iso3
        name
        numcode
        statesRequired
        createdAt
        updatedAt
      }
      createdAt
      firstname
      lastname
      id

      phone
      state {
        name
        abbr
        createdAt
        updatedAt
      }
      stateName
      updatedAt
      zipcode
    }
    email
    id
    lastLoginAt
    shipAddress {
      address1
      address2
      alternativePhone
      city
      company
      country {
        isoName
        iso
        iso3
        name
        numcode
        statesRequired
        createdAt
        updatedAt
      }
      createdAt
      firstname
      lastname
      id

      phone
      state {
        name
        abbr
        createdAt
        updatedAt
      }
      stateName
      updatedAt
      zipcode
    }
    loginCount
    updatedAt
    wallet {
      nodes {
        createdAt
        default
        id
        paymentSource {
          ... on CreditCard {
            address {
              address1
              address2
              alternativePhone
              city
              company
              country {
                isoName
                iso
                iso3
                name
                numcode
                statesRequired
                createdAt
                updatedAt
              }
              createdAt
              firstname
              lastname
              id

              phone
              state {
                name
                abbr
                createdAt
                updatedAt
              }
              stateName
              updatedAt
              zipcode
            }
            ccType
            lastDigits
            month
            name
            year
          }
          createdAt
          updatedAt
          paymentMethod {
            createdAt
            description
            id
            name
            position
            updatedAt
          }
        }
        updatedAt
      }
    }
  }
}
